// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtaQkcYbk_Uqi5RjpHf7qVCeJxUFiLGK0',
    appId: '1:63802077589:web:5a5a796e8b2b228015869c',
    messagingSenderId: '63802077589',
    projectId: 'clothes-app-f4e01',
    authDomain: 'clothes-app-f4e01.firebaseapp.com',
    storageBucket: 'clothes-app-f4e01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3vLnJLnZNxr4EVLWtkp4PdRD6cdjf3M',
    appId: '1:63802077589:android:58f9967cec16a40a15869c',
    messagingSenderId: '63802077589',
    projectId: 'clothes-app-f4e01',
    storageBucket: 'clothes-app-f4e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxzfhDgoKbl2iHj4eR4l32cAl9Ksol4Bo',
    appId: '1:63802077589:ios:f4bba94fde17e54815869c',
    messagingSenderId: '63802077589',
    projectId: 'clothes-app-f4e01',
    storageBucket: 'clothes-app-f4e01.firebasestorage.app',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxzfhDgoKbl2iHj4eR4l32cAl9Ksol4Bo',
    appId: '1:63802077589:ios:f4bba94fde17e54815869c',
    messagingSenderId: '63802077589',
    projectId: 'clothes-app-f4e01',
    storageBucket: 'clothes-app-f4e01.firebasestorage.app',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtaQkcYbk_Uqi5RjpHf7qVCeJxUFiLGK0',
    appId: '1:63802077589:web:22223f7c801cc7f615869c',
    messagingSenderId: '63802077589',
    projectId: 'clothes-app-f4e01',
    authDomain: 'clothes-app-f4e01.firebaseapp.com',
    storageBucket: 'clothes-app-f4e01.firebasestorage.app',
  );

}